image: ubuntu:latest

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - apt update
    - apt install -y cmake build-essential libgtest-dev
  script:
    - mkdir build && cd build
    - cmake .. && make
    - cd ..
  artifacts:
    paths:
      - bin/test_bank_system
      - lib/*
  tags:
    - common
    - cpu

test:
  stage: test
  script:
    - bin/test_bank_system
  tags:
    - common
    - cpu