image: ubuntu:latest

stages:
  - build
  - test
  - coverage

build:
  stage: build
  before_script:
    - apt update
    - apt install -y cmake build-essential libgtest-dev
    - apt-get -y install lcov
  script:
    - mkdir build && cd build
    - cmake .. && make
    - cd ..
  artifacts:
    paths:
      - bin/test_bank_system
      - lib/*
      - code_coverage.info
  tags:
    - common
    - cpu

test:
  stage: test
  before_script:
    - apt update
    - apt install -y cmake build-essential libgtest-dev
    - apt-get -y install lcov
  script:
    - lcov --directory build --capture --output-file code_coverage.info -rc lcov_branch_coverage=1
    - bin/test_bank_system
  artifacts:
    paths:
      - code_coverage.info
  tags:
    - common
    - cpu

coverage:
  stage: coverage
  before_script:
    - apt update
    - apt install -y cmake build-essential libgtest-dev
    - apt-get -y install lcov
  script:
    - genhtml code_coverage.info --branch-coverage --output-directory code_coverage_report
  artifacts:
    paths:
      - code_coverage_report/*
  tags:
    - common
    - cpu